package: watson
version: '2.3.0'
author: Thomas Blum
supportpage: www.redaxo.org/de/forum/

page:
    title: 'translate:watson'
    perm: watson[]
    pjax: false
    icon: watson-navigation-icon
    subpages:
        settings: { title: 'translate:config' }

requires:
    php:
        version: '>=7, <9'

providers:
    - 'Watson\Workflows\Structure\StructureProvider'
    - 'Watson\Workflows\Media\MediaProvider'
    - 'Watson\Workflows\Module\ModuleProvider'
    - 'Watson\Workflows\Template\TemplateProvider'
    - 'Watson\Workflows\Sprog\SprogProvider'
    - 'Watson\Workflows\YForm\YFormProvider'

stylesheets:
    - facebox.css
    - watson.css

javascripts:
    - facebox.js
    - hogan-3.0.2.min.js
    - typeahead.bundle.js
    - watson.js


cheatsheet:
    - \Watson\Cheatsheet\CheatsheetServiceProvider
